source 'http://rubygems.org'

gem 'rails', '3.2.16'
gem 'rake'
gem 'properties-ruby'
gem 'selenium-webdriver'
gem 'rspec-rails'
gem 'rspec', '3.1.0'
gem 'phantomjs'
gem 'yarjuf'
gem 'rspec_junit_formatter'
gem 'rspec-extra-formatters'
gem 'rest-client'
gem 'certified'
gem 'logging'
gem 'sys-proctable'
gem 'addressable'
gem 'parallel_tests'
gem 'rspec_log_formatter'
gem 'allure-rspec'
gem 'rspec-retry'
gem 'rspec-legacy_formatters'
